version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/"
    schedule:
      interval: "weekly"
    assignees:
      - "kirillzhosul"
    commit-message:
      prefix: "[npm] "
  - package-ecosystem: "docker"
    directory: "/src/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[docker] "
    assignees:
      - "kirillzhosul"